// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetAnalysisData, GetAnalysisResponse } from './types.gen';

export class AnalysisService {
    /**
     * Find popular dishes from restaurant reviews
     * Analyzes restaurant reviews to identify the most popular dishes mentioned
     * @param data The data for the request.
     * @param data.query The name of the restaurant to analyze
     * @returns unknown Popular dishes analysis completed successfully
     * @throws ApiError
     */
    public static getAnalysis(data: GetAnalysisData): CancelablePromise<GetAnalysisResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/analysis',
            query: {
                query: data.query
            },
            errors: {
                400: 'Bad request or analysis error',
                500: 'Server error'
            }
        });
    }
    
}