// This file is auto-generated by @hey-api/openapi-ts

export type GetRestaurantsData = {
    /**
     * identifier of the restaurant
     */
    query: string;
    xRecaptchaToken: string;
};

export type GetRestaurantsResponse = ({
    success: boolean;
    restaurants: Array<{
        id: (string) | null;
        name: (string) | null;
        rating: (number) | null;
        reviewCount: (number) | null;
        categories: Array<(string)> | null;
        address: (string) | null;
        priceLevel: (string) | null;
        openNow: boolean;
        phone: (string) | null;
        website: (string) | null;
        photos: Array<(string)>;
        accessibility: Array<(string)> | null;
    }>;
    error?: string;
});

export type GetRestaurantsDishesData = {
    /**
     * identifier of the restaurant
     */
    query: string;
    xRecaptchaToken: string;
};

export type GetRestaurantsDishesResponse = ({
    success: boolean;
    totalReviewsAnalyzed: number;
    popularDishes: Array<{
        /**
         * Name of the dish
         */
        name: string;
        /**
         * Number of mentions in reviews
         */
        mentions: number;
        /**
         * Average rating for this dish (0-5)
         */
        rating: number;
        /**
         * Sentiment score for this dish
         */
        sentimentScore: number;
        /**
         * Excerpts from reviews mentioning this dish
         */
        reviewExcerpts: Array<(string)>;
    }>;
});