// This file is auto-generated by @hey-api/openapi-ts

export type GetRestaurantsData = {
    /**
     * identifier of the restaurant
     */
    query: string;
};

export type GetRestaurantsResponse = ({
    success: boolean;
    query: string;
    placeUrl: string;
    imageUrl: (string) | null;
});

export type GetRestaurantsDishesData = {
    /**
     * identifier of the restaurant
     */
    query: string;
};

export type GetRestaurantsDishesResponse = ({
    success: boolean;
    query: string;
    totalReviewsAnalyzed: number;
    popularDishes: Array<{
        /**
         * Name of the dish
         */
        name: string;
        /**
         * Number of mentions in reviews
         */
        mentions: number;
        /**
         * Average rating for this dish (0-5)
         */
        rating: number;
        /**
         * Sentiment score for this dish
         */
        sentimentScore: number;
        /**
         * Excerpts from reviews mentioning this dish
         */
        reviewExcerpts: Array<(string)>;
    }>;
});